/* Authorization Code flow with PKCE (S256). No client secret in the browser,
   and every endpoint comes from runtime-config.json — nothing generated by
   CloudFormation is hardcoded here. */

let config = null;
let idToken = null;

const $ = (id) => document.getElementById(id);

async function sha256Base64Url(text) {
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return btoa(String.fromCharCode(...new Uint8Array(digest)))
    .replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

function randomString() {
  const bytes = crypto.getRandomValues(new Uint8Array(32));
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

async function signIn() {
  const verifier = randomString();
  sessionStorage.setItem("pkce_verifier", verifier);
  const challenge = await sha256Base64Url(verifier);
  const params = new URLSearchParams({
    client_id: config.cognitoClientId,
    response_type: "code",
    scope: "openid email",
    redirect_uri: config.redirectUri,
    code_challenge_method: "S256",
    code_challenge: challenge,
  });
  window.location.assign(`${config.cognitoDomain}/oauth2/authorize?${params}`);
}

async function exchangeCode(code) {
  const verifier = sessionStorage.getItem("pkce_verifier");
  const response = await fetch(`${config.cognitoDomain}/oauth2/token`, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "authorization_code",
      client_id: config.cognitoClientId,
      code,
      redirect_uri: config.redirectUri,
      code_verifier: verifier,
    }),
  });
  if (!response.ok) throw new Error("Sign-in could not be completed.");
  const tokens = await response.json();
  idToken = tokens.id_token;
  sessionStorage.removeItem("pkce_verifier");
  window.history.replaceState({}, "", config.redirectUri);
}

async function call(path, options = {}) {
  const response = await fetch(`${config.apiUrl}${path}`, {
    ...options,
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${idToken}`,
      ...(options.headers || {}),
    },
  });
  const body = await response.json().catch(() => ({}));
  return { ok: response.ok, status: response.status, body };
}

function show(element, html, kind = "info") {
  element.className = `panel ${kind}`;
  element.innerHTML = html;
}

async function submitTicket() {
  const description = $("description").value.trim();
  const result = $("result");

  if (!description) {
    show(result, "Describe the problem before sending.", "error");
    $("description").focus();
    return;
  }

  $("submit").disabled = true;
  try {
    const { ok, body } = await call("/tickets", {
      method: "POST",
      body: JSON.stringify({ description }),
    });
    if (!ok) {
      show(result, body.error || "The request could not be sent. Try again.", "error");
      return;
    }
    show(
      result,
      `Request sent. Your reference is <strong>${body.ticketId}</strong>. ` +
        `Paste it below to see which team picked it up.`,
      "success"
    );
    $("description").value = "";
    $("lookup").value = body.ticketId;
  } catch {
    show(result, "No response from the helpdesk. Check your connection.", "error");
  } finally {
    $("submit").disabled = false;
  }
}

async function checkStatus() {
  const reference = $("lookup").value.trim();
  const out = $("status-result");
  if (!reference) {
    show(out, "Enter a reference to check.", "error");
    return;
  }

  const { ok, status, body } = await call(`/tickets/${encodeURIComponent(reference)}`);
  if (status === 404) {
    show(out, "No request found with that reference.", "error");
    return;
  }
  if (!ok) {
    show(out, "Status is unavailable right now.", "error");
    return;
  }

  const rows = [
    ["Status", body.status],
    ["Category", body.category],
    ["Priority", body.priority],
    ["Assigned to", body.assignedTeam],
    ["Raised", body.createdAt],
  ]
    .filter(([, value]) => value)
    .map(([label, value]) => `<div><dt>${label}</dt><dd>${value}</dd></div>`)
    .join("");

  show(
    out,
    body.status === "NEW"
      ? "<p>Received. Waiting to be categorised.</p>" + `<dl>${rows}</dl>`
      : `<dl>${rows}</dl>`,
    "success"
  );
}

async function start() {
  config = await (await fetch("runtime-config.json")).json();

  const code = new URLSearchParams(window.location.search).get("code");
  if (code) {
    try {
      await exchangeCode(code);
    } catch {
      /* fall through to the sign-in panel */
    }
  }

  if (idToken) {
    const claims = JSON.parse(atob(idToken.split(".")[1]));
    $("who").textContent = claims.email || "";
    $("account").hidden = false;
    $("signin-panel").hidden = true;
    $("app").hidden = false;
  }

  $("signin").addEventListener("click", signIn);
  $("submit").addEventListener("click", submitTicket);
  $("check").addEventListener("click", checkStatus);
  $("signout").addEventListener("click", () => {
    idToken = null;
    window.location.assign(config.redirectUri);
  });
}

start();
